Repository Google-Developer-Student-Clubs-TUK/2024-Flutter-Project-MyLio, pull requests merged in 2024-12, with the labels that each got.

#21 Design: Resume Title Page 퍼블리싱
  frontend/lib/screens/resume_title.dart
Labels: 퍼블리싱

#25 (#24)be api/resume crud
  backend/src/main/java/com/example/gdgocportfolio/controller/ChatGPTController.java
  backend/src/main/java/com/example/gdgocportfolio/controller/CoverLetterController.java
  backend/src/main/java/com/example/gdgocportfolio/controller/ResumeController.java
  backend/src/main/java/com/example/gdgocportfolio/dto/CoverLetterRequestDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/CoverLetterResponseDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/GenerateCoverLetterRequestDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/GenerateCoverLetterResponseDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/ResumeDto.java
  backend/src/main/java/com/example/gdgocportfolio/entity/CoverLetter.java
  backend/src/main/java/com/example/gdgocportfolio/entity/Resume.java
  backend/src/main/java/com/example/gdgocportfolio/entity/User.java
  backend/src/main/java/com/example/gdgocportfolio/repository/CoverLetterRepository.java
  backend/src/main/java/com/example/gdgocportfolio/repository/ResumeRepository.java
  backend/src/main/java/com/example/gdgocportfolio/service/ChatGPTService.java
  backend/src/main/java/com/example/gdgocportfolio/service/CoverLetterService.java
  backend/src/main/java/com/example/gdgocportfolio/service/ResumeService.java
  backend/src/main/resources/application.yml
Labels: 기능구현

#27 feat: Swagger 명세서 기본 틀 (@Operation, @Schema)
  backend/build.gradle
  backend/src/main/java/com/example/gdgocportfolio/config/SwaggerConfig.java
  backend/src/main/java/com/example/gdgocportfolio/controller/ChatGPTController.java
  backend/src/main/java/com/example/gdgocportfolio/controller/CoverLetterController.java
  backend/src/main/java/com/example/gdgocportfolio/controller/ResumeController.java
  backend/src/main/java/com/example/gdgocportfolio/controller/UserAuthenticationController.java
  backend/src/main/java/com/example/gdgocportfolio/dto/ResumeDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/UserJwtInfoDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/UserLoginRequestDto.java
  backend/src/main/java/com/example/gdgocportfolio/dto/UserRegisterRequestDto.java
  backend/src/main/resources/application.yml
Labels: 백엔드
