Repository Google-Developer-Student-Clubs-TUK/2024-Flutter-Project-MyLio, pull requests merged in 2025-02, with the labels that each got.

#83 (#82)fe feat/jwt token
  frontend/lib/screens/Login.dart
  frontend/lib/screens/my_resume_create_page.dart
  frontend/lib/screens/my_resume_screen.dart
  frontend/lib/utils/http_interceptor.dart
  frontend/linux/flutter/generated_plugin_registrant.cc
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.yaml
  frontend/windows/flutter/generated_plugin_registrant.cc
Labels: 프론트엔드

#88 Feat: 이력서 페이지 수정 API 연동
  frontend/lib/screens/edit.dart
  frontend/lib/screens/my_resume_screen.dart
  frontend/lib/screens/resume/resume_title.dart
Labels: API 연동, 프론트엔드

#90 Feat: 이력서 복제 API 연동
  frontend/lib/screens/my_resume_screen.dart
Labels: API 연동, 프론트엔드

#92 Feat: 이력서 수정 API 모두 연동
  frontend/lib/screens/edit.dart
  frontend/lib/screens/resume/activity_experience.dart
  frontend/lib/screens/resume/capability_page.dart
  frontend/lib/screens/resume/industrial_group.dart
  frontend/lib/screens/resume/job_duty.dart
  frontend/lib/screens/resume/strength_page.dart
  frontend/lib/screens/resume/weakness_page.dart
Labels: API 연동, 프론트엔드

#95 Feat: 기본정보 페이지 API 연동
  frontend/lib/screens/base_info.dart
Labels: API 연동, 프론트엔드

#97 Feat: 자기소개서 수정 페이지 구현
  frontend/lib/screens/components/introduction_list_PopupMeun_Btn.dart
  frontend/lib/screens/coverletter_edit.dart
  frontend/lib/screens/introduction_list.dart
Labels: 기능구현, 프론트엔드
