Repository Google-Developer-Student-Clubs-TUK/2024-Flutter-Project-MyLio, pull requests merged in 2025-01, with the labels that each got.

#33 Design: Login 및 Signup 디자인 수정
  frontend/lib/screens/Login.dart
  frontend/lib/screens/Signup.dart
Labels: 퍼블리싱

#36 Design: 이력서 수정 페이지 퍼블리싱
  frontend/lib/screens/edit.dart
Labels: 퍼블리싱

#40 (#37) Feat: 이력서 전체 페이지 구현 및 폴더 구조 정리
  frontend/lib/screens/award_page.dart
  frontend/lib/screens/components/bottom_bar.dart
  frontend/lib/screens/edit.dart
  frontend/lib/screens/home_screen.dart
  frontend/lib/screens/industrial_group.dart
  frontend/lib/screens/introduction_list.dart
  frontend/lib/screens/job_duty.dart
  frontend/lib/screens/loading_screen.dart
  frontend/lib/screens/my_resume_create_page.dart
  frontend/lib/screens/my_resume_screen.dart
  frontend/lib/screens/question_insert.dart
  frontend/lib/screens/question_result.dart
  frontend/lib/screens/resume/activity_experience.dart
  frontend/lib/screens/resume/award_page.dart
  frontend/lib/screens/resume/capability_page.dart
  frontend/lib/screens/resume/certificate_page.dart
  frontend/lib/screens/resume/industrial_group.dart
  frontend/lib/screens/resume/job_duty.dart
  frontend/lib/screens/resume/language_page.dart
  frontend/lib/screens/resume/resume_title.dart
  frontend/lib/screens/resume/strength_page.dart
  frontend/lib/screens/resume/weakness_page.dart
  frontend/lib/screens/resume_title.dart
  frontend/lib/screens/setting_screen.dart
  frontend/lib/screens/theme/app_colors.dart
  frontend/lib/screens/widgets/my_resume_empty_widget.dart
  frontend/lib/screens/widgets/resume_PopupMenu_Btn.dart
Labels: 기능구현, 프론트엔드

#42 Design: 이력서 페이지 부분 디자인 수정1
  frontend/lib/screens/resume/capability_page.dart
  frontend/lib/screens/resume/industrial_group.dart
  frontend/lib/screens/resume/job_duty.dart
  frontend/lib/screens/resume/resume_title.dart
  frontend/lib/screens/resume/strength_page.dart
  frontend/lib/screens/resume/weakness_page.dart
Labels: 퍼블리싱, 프론트엔드

#45 Fix: 날짜 형식 YYYY-MM-DD로 통일
  frontend/lib/screens/resume/activity_experience.dart
  frontend/lib/screens/resume/award_page.dart
  frontend/lib/screens/resume/certificate_page.dart
  frontend/lib/screens/resume/language_page.dart
Labels: 프론트엔드

#57 (#55)be api/error message
  backend/src/main/java/com/example/gdgocportfolio/controller/UserAuthenticationController.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/CoverLetterException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/CoverLetterNotExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/IncorrectPasswordException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/InvalidUserException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/PasswordException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/PrimaryResumeNotExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/QuestionAnswerNotExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/ResumeException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/ResumeNotExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/UserException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/UserExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/UserExistsWithPhoneNumberException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/UserNotExistsException.java
  backend/src/main/java/com/example/gdgocportfolio/exceptions/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/example/gdgocportfolio/service/ChatGPTService.java
  backend/src/main/java/com/example/gdgocportfolio/service/CoverLetterService.java
  backend/src/main/java/com/example/gdgocportfolio/service/QuestionAnswerService.java
  backend/src/main/java/com/example/gdgocportfolio/service/ResumeService.java
Labels: 기능구현, 백엔드

#61 (#58, 59)be api/error fix
  backend/src/main/java/com/example/gdgocportfolio/exceptions/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/example/gdgocportfolio/service/ResumeService.java
Labels: 이슈 해결

#73 Fix: Language 필드명 exam에서 examName으로 변경
  frontend/lib/screens/my_resume_create_page.dart
Labels: 프론트엔드

#74 Fix: ActivityExperience에 초기 데이터 initialActivities 전달 및 디자인 수정
  frontend/lib/screens/edit.dart
  frontend/lib/screens/resume/activity_experience.dart
Labels: 프론트엔드
